#!/bin/bash

# Dependencies
# https://github.com/Zaharid/pandoc_static_katex
# Pandoc

# Make sure current folder as the newest one
# To generate list in homepage
touch . 

# Asking User for Math Rendering
read -rp "Use math? (y/n): " INTR

# Converting Markdown to HTML
# Also removing the first Line (h1)
if [ "$INTR" == "n" ]; then
    HTML=$(pandoc -f markdown -t html index.md --highlight-style zenburn | tail -n +2 )
else
    HTML=$(pandoc -s index.md --filter pandoc-static-katex -t html5 --css https://cdn.jsdelivr.net/npm/katex@0.13.5/dist/katex.min.css --highlight-style zenburn | sed '/<\/h1>/d')
fi


# GETTING DOCUMENT TITLE
# Should be in the first line of Markdown file
MD=$(head -n 1 < index.md)


read -rp "Article Titlebar: " TITLE
read -rp "Article Description: " DESC


# The index.md file and this script
# should be in the same directory

# Input md file should be named index.md
# The output HTML file will be index.html
cat << EOF > index.html
<html>
<head>
<title>${TITLE} - Jhagas's Blog</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<link rel="stylesheet" href="../assets/css/main.css" />
</head>
<body class="single is-preload">
<div id="wrapper">
<header id="header">
<h1><a href="https://jhagas.github.io/blog">Jhagas's Blog</a></h1>
</header>
<div id="main">
<article class="post">
<header>
<div class="title">
<h2>${MD#* }</a></h2>
<p>${DESC}</p>
<time class="published" datetime="$(date "+%Y-%m-%d")">$(date "+%A, %d %B %Y")</time>
</div>
</header>
<span class="image featured"><img src="images/judul.png" alt="" /></span>
${HTML}
</article>
</div>
<section id="footer">
<p class="social">Follow me on <a href="https://qoto.org/web/accounts/438673">Mastodon</a></p>
<p class="copyright">&copy; Jhagas Hana Winaya, Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/legalcode">CC-BY-SA 3.0,</a> <a href="https://github.com/jhagas/blog">(Source Code)</a>.</p>
</section>
</div>
</body>
</html>
EOF

cd .. && ./homebuild
