#!/bin/bash

ls -tr1 | grep "-" | sed 's/^/(jhagas.github.io\/blog\//; s/$/)/' > temp

paste -d']' list temp | sed 's/^/1. [/' > index.md

HTML=$(pandoc -f gfm -t html index.md)

cat << EOF > index.html
<html>
	<head>
		<title>Selamat Datang - Jhagas's Blog</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="single is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="https://jhagas.github.io/blog">Jhagas's Blog</a></h1>
					</header>

				<!-- Main -->
					<div id="main">

<article class="post">
	<header>
		<div class="title">
			<h2>Halo, Selamat Datang!</a></h2>
            <p>Sebuah blog sederhana yang berisi tentang hal-hal menarik di bidang STEM (Science, Technology, Engineering, Mathematics)<br>
            Ditulis oleh Jhagas Hana Winaya</p>
		</div>
	</header>

				<!-- Post -->

<h2 class="atx" id="list-artikel">List Artikel</h2>
${HTML}
</article>
</div>

					<!-- Footer -->
					<section id="footer">
                        <p class="social">Follow me on <a href="https://qoto.org/web/accounts/438673">Mastodon</a></p>
                        <p class="copyright">&copy; Jhagas Hana Winaya, Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/legalcode">CC-BY-SA 3.0,</a> <a href="https://github.com/jhagas/blog">(Source Code)</a>.</p>
					</section>
			</div>
	</body>
</html>

EOF

rm temp index.md
