#!/bin/bash

find . -name index.md -printf "\n%C+ %p" -exec head -n1 {} \; | sort -t+ -k1r -k2r | cut -d# -f 2 | cut -c2- | sed  '/^$/d' > list

ls -t1 | grep "-" | sed 's/^/(/; s/$/)/' > temp

paste -d']' list temp | sed 's/^/- [/' > index.md

HTML=$(pandoc -f gfm -t html index.md)

cat << EOF > index.html
<html>
<head>
<title>Selamat Datang - Jhagas's Blog</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<link rel="stylesheet" href="assets/css/main.css" />
</head>
<body class="single is-preload">
<div id="wrapper">
<header id="header">
<h1><a href="https://jhagas.github.io/blog">Jhagas's Blog</a></h1>
</header>
<div id="main">
<article class="post">
<header>
<div class="title">
<h2>Halo, Selamat Datang!</a></h2>
<p>Sebuah blog sederhana yang membahas hal-hal menarik di bidang STEM (Science, Technology, Engineering, Mathematics)<br>Ditulis oleh Jhagas Hana Winaya</p>
</div>
</header>
<h2 class="atx" id="daftar-artikel">Daftar Artikel</h2>
<blockquote>
<p>Daftar artikel berikut diurutkan dari post terbaru. Saya tidak akan menerapkan fitur pencarian di blog ini, silahkan gunakan fitur <strong>"Cari di halaman"</strong> pada peramban anda. Jika anda memakai komputer atau laptop, anda bisa mulai melakukan pencarian dengan pintasan keyboard <strong>Ctrl+f</strong></p>
</blockquote>
${HTML}
</article>
</div>
<section id="footer">
<p class="social">Follow me on <a href="https://qoto.org/web/accounts/438673">Mastodon</a></p>
<p class="copyright">&copy; Jhagas Hana Winaya, Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/legalcode">CC-BY-SA 3.0,</a> <a href="https://github.com/jhagas/blog">(Source Code)</a>.</p>
</section>
</div>
</body>
</html>
EOF

rm temp index.md list
